---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  namespace: work
  labels:
    app: &app nginx
    version: &version 1.27.5
spec:
  replicas: 3
  selector:   
    matchLabels:      # Works with pods that match these labels (with nginx and version 1.27.5) in our case
      app: *app       # reffering to the app label defined in metadata.labels(app: &app nginx)
      version: *version # reffering to the version label defined in metadata.labels(version: &version 1.27.5)
  template:
    metadata:
      labels:
        app: *app
        version: *version
    spec:
      initContainers:
        - name: init-container
          image: busybox:1.28
          command: 
            - 'sh'
            - '-c'
            - 'echo Initializing... && sleep 10'
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10